version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "00:00"
      timezone: "Africa/Cairo"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "00:00"
      timezone: "Africa/Cairo"
